setwd("~/rvtests/DajinagDataSet")
ped = read.table("qt1.ped", header = F, strings = F)
vcf = read.table("qt1.vcf", header = F, strings = F)
head(vcf)
np = ncol(vcf)
geno.vcf = t(vcf[,10:np])
dim(geno.vcf)
geno.ped = ped[, 7:ncol(ped)]
dim(geno.ped)
all(geno.vcf == geno.ped)

pheno = read.table("qt1.pheno", header = F, strings = F)
all(pheno[,1] == ped[,1])
all(pheno[,2] == ped[,2])
all(pheno[,3] == ped[,6])